##################################################################
# MICROPROCESSOR-BASED SYSTEMS
# LAB SESSION 2
# FILE: MAKEFILE
# AUTHORS: Emilio Cuesta Fernandez - Alejandro Sanchez Sanz
# COUPLE NUMBER: 8
# GROUP: 2351
##################################################################


all: dec2asc.exe labs2a.exe labs2b.exe

dec2asc.exe: dec2asc.obj
    tlink /v dec2asc

labs2a.exe: labs2a.obj
    tlink /v labs2a

labs2b.exe: labs2b.obj
    tlink /v labs2b

dec2asc.obj: dec2asc.asm
    tasm /zi dec2asc.asm ,, dec2asc.lst

labs2a.obj: labs2a.asm
    tasm /zi labs2a.asm ,, labs2a.lst

labs2b.obj: labs2b.asm
    tasm /zi labs2b.asm ,, labs2b.lst

clean: 
    del *.exe
    del *.obj
    del *.lst
    del *.map
    
